[build]
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  VITE_API_KEY = "AIzaSyDbjiftBKkWeJ_89lAy4HW0T6FwvyHRTgE"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200